apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
spec:  
  type: ClusterIP
  selector:
    key: registry-pod
  ports:
    - name: cluster-registry
      protocol: TCP
      port: 48103
      targetPort: 5000
