apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  strategy: allInOne
  name: simplest
  storage:
    type: badger
    options:
      badger:
        ephemeral: true
        directory-key: /badger/key
        directory-value: /badger/data
  volumeMounts:
  - name: data
    mountPath: /badger
  volumes:
  - name: data
    emptyDir: {}