apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-network-deployment    
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      key: tools-network-pod
  template:
    metadata:
      labels:
        key: tools-network-pod
    spec:
      containers:
      - name: container
        image: nicolaka/netshoot:latest             