apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana-deployment     
  namespace: monitoring
  labels:
    app: monitoring  
spec:
  replicas: 1
  selector:
    matchLabels:
      key: monitoring-grafana-pod
  template:
    metadata:
      labels:
        key: monitoring-grafana-pod
    spec:      
      containers:
      - name: grafana-container
        image: grafana/grafana        
        env:          
          - name: GF_SECURITY_ADMIN_USER
            value: "admin"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "admin123"
          - name: GF_INSTALL_PLUGINS
            value: grafana-kubernetes-app          
          
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources/
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards/
            name: grafana-dashboards
            readOnly: false
          - mountPath: /var/lib/grafana/dashboards/
            name: grafana-dashboards-samples
            readOnly: false
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
            defaultMode: 420
            name: grafana-datasources
      - name: grafana-dashboards
        configMap:
            defaultMode: 420
            name: grafana-dashboards

      - name: grafana-dashboards-samples
        configMap:
            defaultMode: 420
            name: grafana-dashboards-samples
