apiVersion: v1
kind: Service
metadata:
  name: state-service
  namespace: owlvey
spec:
  # ClusterIP NodePort LoadBalancer
  type: ClusterIP
  selector:
    app: owlvey-state-pod-app
  ports:
    - name: db
      protocol: TCP
      port: 80
      targetPort: 1433
#     nodePort: 31234
