name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: commitStage   
  jobs:    
  - job:    
    pool:
      vmImage: 'ubuntu-latest'        
    steps:
    - checkout: self    
    - checkout: github://owlvey/owlvey_falcon_ui
 

