name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: commitStage   
  jobs:    
  - job:    
    pool:
      vmImage: 'ubuntu-latest'    
    workspace:
    clean: outputs | resources | all # what to clean up before the job runs
    steps:
    - checkout: self    
 

