name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  - repository: falconUI # The name used to reference this repository in the checkout step
    type: github
    endpoint: owlvey
    name: owlvey/owlvey_falcon_ui
stages:
- stage: commitStage   
  jobs:    
  - job:    
    pool:
      vmImage: 'ubuntu-latest'        
    steps:
    - checkout: self    
    - checkout: falconUI    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Owlvey Docker Connection'
        dockerComposeFile: './containers/owlvey_falcon_ui/docker-compose.yml'
        action: 'Build services'
        includeSourceTags: true
        includeLatestTag: true
 
