apiVersion: v1
kind: Service
metadata:
  name: authority-service
  namespace: owlvey
spec:
  # ClusterIP NodePort LoadBalancer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 47002
      targetPort: 47002
#     nodePort: 31234
---
apiVersion: v1
kind: Endpoints
apiVersion: v1
metadata:
 name: authority-service
 namespace: owlvey
subsets:
 - addresses:
     - ip: 192.168.0.14
   ports:
     - port: 47002
