apiVersion: v1
kind: Service
metadata:
  name: authority-service
  namespace: owlvey
spec:
  # ClusterIP NodePort LoadBalancer
  type: ClusterIP
  selector:
    app: owlvey-authority-pod-app
  ports:
    - name: site
      protocol: TCP      
      port: 47002
      targetPort: 80 
#     nodePort: 31234