apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-jaeger-deployment    
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      key: tracing-jaeger-pod
  template:
    metadata:
      labels:
        key: tracing-jaeger-pod
    spec:
      containers:
      - name: container
        image: jaegertracing/all-in-one        
        args:
        - --log-level=debug
        ports:
            - containerPort: 9411
              name: jaeger-port
            - containerPort: 16686
              name: listerner-port
        env:
          - name: "COLLECTOR_ZIPKIN_HTTP_PORT"
            value: "9411"
---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: tracing
spec:  
  type: ClusterIP
  selector:
    key: tracing-jaeger-pod
  ports:
    - name: jaeger
      protocol: TCP      
      port: 9411
      targetPort: 9411
    - name: admin
      protocol: TCP      
      port: 48100
      targetPort: 16686

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-route  
  namespace: tracing
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`jaeger.cluster.com`) 
    kind: Rule
    services:
    - name: jaeger-service
      port: 48100
      